"""Automatic Disc Ripper for Windows Setup GUI — tkinter-based configuration helper.

Helps new users configure Automatic Disc Ripper for Windows by providing a friendly GUI
with file/directory pickers, validation, and save-to-YAML functionality.

Launch standalone:   python setup_gui.py
Launch from venv:    .venv\\Scripts\\python.exe setup_gui.py
"""

import os
import sys
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent
CONFIG_DIR = PROJECT_ROOT / "config"
CONFIG_PATH = CONFIG_DIR / "adr.yaml"
EXAMPLE_PATH = CONFIG_DIR / "adr.yaml.example"
PRESETS_DIR = PROJECT_ROOT / "presets"

# ---------------------------------------------------------------------------
# Load/save helpers (inline to avoid importing adr.* which needs deps)
# ---------------------------------------------------------------------------

def _load_yaml(path: Path) -> dict:
    """Load a YAML file.  Uses PyYAML if available, otherwise basic parsing."""
    try:
        import yaml
        with open(path, "r", encoding="utf-8") as fh:
            return yaml.safe_load(fh) or {}
    except ImportError:
        # Minimal fallback — read key: value pairs (no nested structures)
        data: dict = {}
        with open(path, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if ":" in line:
                    key, _, val = line.partition(":")
                    val = val.strip()
                    if val.lower() in ("true", "false"):
                        data[key.strip()] = val.lower() == "true"
                    elif val.isdigit():
                        data[key.strip()] = int(val)
                    else:
                        data[key.strip()] = val.strip("'\"")
        return data


def _save_yaml(path: Path, data: dict) -> None:
    """Save config to YAML."""
    try:
        import yaml
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            yaml.dump(data, fh, default_flow_style=False, allow_unicode=True)
    except ImportError:
        # Minimal fallback
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("# Automatic Disc Ripper for Windows configuration (generated by setup GUI)\n\n")
            for key, val in data.items():
                if isinstance(val, bool):
                    fh.write(f"{key}: {'true' if val else 'false'}\n")
                elif isinstance(val, list):
                    fh.write(f"{key}: []\n")
                elif isinstance(val, dict):
                    fh.write(f"{key}: {{}}\n")
                else:
                    fh.write(f"{key}: {val}\n")


def _discover_preset_files() -> list[str]:
    """Return names of .json preset files in presets/ directory."""
    if not PRESETS_DIR.is_dir():
        return []
    return sorted(f.name for f in PRESETS_DIR.glob("*.json"))


# ---------------------------------------------------------------------------
# Defaults (mirrors adr/config.py _DEFAULTS)
# ---------------------------------------------------------------------------
DEFAULTS = {
    "makemkv_path": r"C:\Program Files (x86)\MakeMKV\makemkvcon64.exe",
    "handbrake_path": r"C:\Program Files\HandBrake\HandBrakeCLI.exe",
    "raw_path": r"C:\ADR\raw",
    "completed_path": r"C:\ADR\completed",
    "plex_path": "",
    "watch_path": "",
    "watch_output_path": "",
    "tmdb_api_key": "",
    "handbrake_preset": "Fast 1080p30",
    "handbrake_preset_file": "",
    "handbrake_extra_args": "",
    "min_title_length": 120,
    "max_encode_jobs": 1,
    "watch_interval": 5,
    "web_host": "0.0.0.0",
    "web_port": 8080,
    "log_level": "INFO",
    "drives": "auto",
    "disabled_drives": [],
    "eject_after_rip": True,
    "no_eject_drives": [],
    "main_feature_only": True,
    "auto_move_to_plex": True,
    "drive_labels": {},
}


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def _check_exe(path_str: str, name: str) -> str | None:
    """Return warning string if exe is missing, else None."""
    if not path_str:
        return f"{name}: no path specified"
    if not Path(path_str).is_file():
        return f"{name}: file not found ({path_str})"
    return None


# ---------------------------------------------------------------------------
# Main GUI
# ---------------------------------------------------------------------------

class SetupGUI:
    """Automatic Disc Ripper for Windows configuration GUI."""

    SECTION_COLORS = {
        "tools": "#2563eb",      # blue
        "dirs": "#059669",       # green
        "tmdb": "#d97706",       # amber
        "handbrake": "#7c3aed",  # violet
        "options": "#dc2626",    # red
        "web": "#0891b2",        # cyan
    }

    def __init__(self, root: tk.Tk):
        self.root = root
        self.root.title("Automatic Disc Ripper for Windows Setup")
        self.root.resizable(True, True)
        self.root.minsize(640, 500)

        # Try to set a reasonable starting size
        self.root.geometry("740x720")

        # Style
        style = ttk.Style()
        style.theme_use("clam" if "clam" in style.theme_names() else "default")

        # Load existing config or defaults
        self.config_data = dict(DEFAULTS)
        if CONFIG_PATH.exists():
            try:
                loaded = _load_yaml(CONFIG_PATH)
                self.config_data.update(loaded)
            except Exception:
                pass  # stick with defaults
        elif EXAMPLE_PATH.exists():
            try:
                loaded = _load_yaml(EXAMPLE_PATH)
                self.config_data.update(loaded)
            except Exception:
                pass

        # Variables dict
        self.vars: dict[str, tk.Variable] = {}

        self._build_ui()

    # ------------------------------------------------------------------ #
    # UI construction
    # ------------------------------------------------------------------ #

    def _build_ui(self):
        # Header
        header = ttk.Frame(self.root)
        header.pack(fill="x", padx=12, pady=(12, 4))
        ttk.Label(header, text="Automatic Disc Ripper for Windows Setup",
                  font=("Segoe UI", 16, "bold")).pack(side="left")
        status_text = "config\\adr.yaml found" if CONFIG_PATH.exists() else "no config found"
        ttk.Label(header, text=f"({status_text})",
                  font=("Segoe UI", 9)).pack(side="left", padx=(10, 0))

        # Scrollable content area
        container = ttk.Frame(self.root)
        container.pack(fill="both", expand=True, padx=12, pady=4)

        canvas = tk.Canvas(container, highlightthickness=0)
        scrollbar = ttk.Scrollbar(container, orient="vertical", command=canvas.yview)
        self.scroll_frame = ttk.Frame(canvas)

        self.scroll_frame.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all"))
        )
        canvas.create_window((0, 0), window=self.scroll_frame, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)

        canvas.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")

        # Mouse wheel scrolling
        def _on_mousewheel(event):
            canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")
        canvas.bind_all("<MouseWheel>", _on_mousewheel)

        # --- Sections ---
        self._section_tools()
        self._section_directories()
        self._section_tmdb()
        self._section_handbrake()
        self._section_options()
        self._section_web()

        # --- Bottom buttons ---
        btn_frame = ttk.Frame(self.root)
        btn_frame.pack(fill="x", padx=12, pady=(4, 12))

        ttk.Button(btn_frame, text="Validate", command=self._validate).pack(side="left", padx=(0, 6))
        ttk.Button(btn_frame, text="Save config\\adr.yaml", command=self._save).pack(side="left", padx=(0, 6))
        ttk.Button(btn_frame, text="Cancel", command=self.root.destroy).pack(side="right")

    def _add_section(self, title: str, color: str = "#333") -> ttk.LabelFrame:
        """Add a labeled section frame."""
        frame = ttk.LabelFrame(self.scroll_frame, text=f"  {title}  ",
                               padding=(10, 6))
        frame.pack(fill="x", pady=(8, 0))
        return frame

    def _file_row(self, parent: ttk.Frame, label: str, key: str,
                  filetypes: list[tuple[str, str]] | None = None) -> None:
        """Add a row with label, entry, and file browse button."""
        row = ttk.Frame(parent)
        row.pack(fill="x", pady=2)
        ttk.Label(row, text=label, width=22, anchor="w").pack(side="left")
        var = tk.StringVar(value=str(self.config_data.get(key, "")))
        self.vars[key] = var
        entry = ttk.Entry(row, textvariable=var)
        entry.pack(side="left", fill="x", expand=True, padx=(0, 4))

        def browse():
            ft = filetypes or [("Executable", "*.exe"), ("All files", "*.*")]
            path = filedialog.askopenfilename(
                title=f"Select {label}",
                filetypes=ft,
                initialdir=str(Path(var.get()).parent) if var.get() and Path(var.get()).parent.exists() else None,
            )
            if path:
                var.set(path)

        ttk.Button(row, text="Browse...", width=12, command=browse).pack(side="right")

    def _dir_row(self, parent: ttk.Frame, label: str, key: str) -> None:
        """Add a row with label, entry, and directory browse button."""
        row = ttk.Frame(parent)
        row.pack(fill="x", pady=2)
        ttk.Label(row, text=label, width=22, anchor="w").pack(side="left")
        var = tk.StringVar(value=str(self.config_data.get(key, "")))
        self.vars[key] = var
        entry = ttk.Entry(row, textvariable=var)
        entry.pack(side="left", fill="x", expand=True, padx=(0, 4))

        def browse():
            initial = var.get() if var.get() and Path(var.get()).exists() else None
            path = filedialog.askdirectory(title=f"Select {label}", initialdir=initial)
            if path:
                var.set(path)

        ttk.Button(row, text="Browse...", width=12, command=browse).pack(side="right")

    def _entry_row(self, parent: ttk.Frame, label: str, key: str,
                   show: str = "", width: int | None = None) -> None:
        """Add a simple label + entry row."""
        row = ttk.Frame(parent)
        row.pack(fill="x", pady=2)
        ttk.Label(row, text=label, width=22, anchor="w").pack(side="left")
        var = tk.StringVar(value=str(self.config_data.get(key, "")))
        self.vars[key] = var
        entry = ttk.Entry(row, textvariable=var, show=show)
        if width:
            entry.configure(width=width)
            entry.pack(side="left", padx=(0, 4))
        else:
            entry.pack(side="left", fill="x", expand=True, padx=(0, 4))

    def _check_row(self, parent: ttk.Frame, label: str, key: str) -> None:
        """Add a checkbox row."""
        row = ttk.Frame(parent)
        row.pack(fill="x", pady=2)
        var = tk.BooleanVar(value=bool(self.config_data.get(key, False)))
        self.vars[key] = var
        ttk.Checkbutton(row, text=label, variable=var).pack(side="left")

    def _combo_row(self, parent: ttk.Frame, label: str, key: str,
                   values: list[str]) -> None:
        """Add a label + combobox row."""
        row = ttk.Frame(parent)
        row.pack(fill="x", pady=2)
        ttk.Label(row, text=label, width=22, anchor="w").pack(side="left")
        var = tk.StringVar(value=str(self.config_data.get(key, "")))
        self.vars[key] = var
        combo = ttk.Combobox(row, textvariable=var, values=values, state="normal")
        combo.pack(side="left", fill="x", expand=True, padx=(0, 4))

    # ------------------------------------------------------------------ #
    # Sections
    # ------------------------------------------------------------------ #

    def _section_tools(self):
        frame = self._add_section("Tools (MakeMKV & HandBrake)")
        self._file_row(frame, "MakeMKV (makemkvcon64):", "makemkv_path")
        self._file_row(frame, "HandBrakeCLI:", "handbrake_path")

    def _section_directories(self):
        frame = self._add_section("Directories")
        self._dir_row(frame, "Rip folder (raw):", "raw_path")
        self._dir_row(frame, "Completed files:", "completed_path")
        self._dir_row(frame, "Plex library:", "plex_path")
        # Separator + watch dirs
        ttk.Separator(frame, orient="horizontal").pack(fill="x", pady=6)
        ttk.Label(frame, text="Watch folder (auto-encode loose files):",
                  font=("Segoe UI", 8, "italic")).pack(anchor="w")
        self._dir_row(frame, "Watch input:", "watch_path")
        self._dir_row(frame, "Watch output:", "watch_output_path")

    def _section_tmdb(self):
        frame = self._add_section("TMDb (movie identification)")
        self._entry_row(frame, "TMDb API key:", "tmdb_api_key")
        hint = ttk.Label(frame,
                         text="Get free key: https://www.themoviedb.org/settings/api",
                         font=("Segoe UI", 8), foreground="#666")
        hint.pack(anchor="w", padx=(0, 0), pady=(0, 2))
        env_hint = ttk.Label(frame,
                             text="Tip: you can also set the environment variable ADR_TMDB_API_KEY instead.",
                             font=("Segoe UI", 8), foreground="#666")
        env_hint.pack(anchor="w")

    def _section_handbrake(self):
        frame = self._add_section("HandBrake Settings")

        # Preset name — combo with common built-in presets
        builtin_presets = [
            "Fast 1080p30",
            "HQ 1080p30 Surround",
            "Super HQ 1080p30 Surround",
            "Fast 720p30",
            "HQ 720p30 Surround",
            "Fast 480p30",
        ]
        self._combo_row(frame, "Preset name:", "handbrake_preset", builtin_presets)

        # Preset file — file picker + auto-discovered presets
        discovered = _discover_preset_files()
        if discovered:
            ttk.Label(frame,
                      text=f"Preset files in presets/: {', '.join(discovered)}",
                      font=("Segoe UI", 8), foreground="#666").pack(anchor="w", pady=(4, 0))

        self._file_row(frame, "Preset file (.json):", "handbrake_preset_file",
                       filetypes=[("JSON preset", "*.json"), ("All files", "*.*")])
        hint = ttk.Label(frame,
                         text="Leave empty to auto-discover from presets/ folder.",
                         font=("Segoe UI", 8), foreground="#666")
        hint.pack(anchor="w")

        self._entry_row(frame, "Extra HandBrake args:", "handbrake_extra_args")

        # Numeric fields
        row = ttk.Frame(frame)
        row.pack(fill="x", pady=2)
        ttk.Label(row, text="Min title length (sec):", width=22, anchor="w").pack(side="left")
        min_var = tk.StringVar(value=str(self.config_data.get("min_title_length", 120)))
        self.vars["min_title_length"] = min_var
        ttk.Entry(row, textvariable=min_var, width=8).pack(side="left")

        row2 = ttk.Frame(frame)
        row2.pack(fill="x", pady=2)
        ttk.Label(row2, text="Max parallel jobs:", width=22, anchor="w").pack(side="left")
        jobs_var = tk.StringVar(value=str(self.config_data.get("max_encode_jobs", 1)))
        self.vars["max_encode_jobs"] = jobs_var
        ttk.Entry(row2, textvariable=jobs_var, width=8).pack(side="left")

    def _section_options(self):
        frame = self._add_section("General Settings")
        self._check_row(frame, "Eject disc automatically after ripping", "eject_after_rip")
        self._check_row(frame, "Rip main feature only (longest)", "main_feature_only")
        self._check_row(frame, "Automatically move to Plex after encode", "auto_move_to_plex")

        # Log level
        log_levels = ["DEBUG", "INFO", "WARNING", "ERROR"]
        self._combo_row(frame, "Log level:", "log_level", log_levels)

    def _section_web(self):
        frame = self._add_section("Web Interface")
        self._entry_row(frame, "Host:", "web_host", width=20)
        self._entry_row(frame, "Port:", "web_port", width=8)

        row = ttk.Frame(frame)
        row.pack(fill="x", pady=2)
        ttk.Label(row, text="Watch interval (sec):", width=22, anchor="w").pack(side="left")
        wi_var = tk.StringVar(value=str(self.config_data.get("watch_interval", 5)))
        self.vars["watch_interval"] = wi_var
        ttk.Entry(row, textvariable=wi_var, width=8).pack(side="left")

    # ------------------------------------------------------------------ #
    # Actions
    # ------------------------------------------------------------------ #

    def _collect(self) -> dict:
        """Collect current form values into a config dict."""
        data = dict(self.config_data)  # start with full existing config

        for key, var in self.vars.items():
            if isinstance(var, tk.BooleanVar):
                data[key] = var.get()
            else:
                val_str = var.get().strip()
                # Try to preserve numeric types
                if key in ("min_title_length", "max_encode_jobs", "web_port"):
                    try:
                        data[key] = int(val_str)
                    except ValueError:
                        data[key] = val_str
                elif key == "watch_interval":
                    try:
                        data[key] = int(val_str) if "." not in val_str else float(val_str)
                    except ValueError:
                        data[key] = val_str
                else:
                    data[key] = val_str

        return data

    def _validate(self) -> list[str]:
        """Validate current settings. Returns list of warnings."""
        data = self._collect()
        warnings = []

        # Check executables
        for key, name in [("makemkv_path", "MakeMKV"), ("handbrake_path", "HandBrakeCLI")]:
            w = _check_exe(data.get(key, ""), name)
            if w:
                warnings.append(w)

        # Check required directories
        for key, name in [("raw_path", "Rip folder"), ("completed_path", "Completed files")]:
            val = data.get(key, "")
            if not val:
                warnings.append(f"{name}: no path specified")

        # TMDb key
        if not data.get("tmdb_api_key", ""):
            warnings.append("TMDb API key missing (movie identification will not work)")

        # Numeric validation
        for key, name in [("min_title_length", "Min title length"),
                          ("max_encode_jobs", "Max jobs"),
                          ("web_port", "Port")]:
            val = data.get(key, "")
            try:
                n = int(val)
                if n <= 0:
                    warnings.append(f"{name}: must be > 0")
            except (ValueError, TypeError):
                warnings.append(f"{name}: must be an integer")

        # Plex path + auto_move
        if data.get("auto_move_to_plex") and not data.get("plex_path", ""):
            warnings.append("Auto-move to Plex is on, but no Plex folder specified")

        # Show result
        if warnings:
            msg = "Warnings:\n\n" + "\n".join(f"  - {w}" for w in warnings)
            messagebox.showwarning("Validation", msg)
        else:
            messagebox.showinfo("Validation", "Everything looks good!")

        return warnings

    def _save(self):
        """Save configuration to config/adr.yaml."""
        data = self._collect()

        # Confirm overwrite if file exists
        if CONFIG_PATH.exists():
            ok = messagebox.askyesno(
                "Confirm",
                "config\\adr.yaml already exists.\n\nDo you want to overwrite it?"
            )
            if not ok:
                return

        try:
            _save_yaml(CONFIG_PATH, data)
            messagebox.showinfo(
                "Saved",
                f"Configuration saved to:\n{CONFIG_PATH}\n\n"
                "Start Automatic Disc Ripper for Windows with start.bat"
            )
        except Exception as exc:
            messagebox.showerror("Error", f"Could not save:\n{exc}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    root = tk.Tk()

    # Set window icon if favicon exists
    icon_path = PROJECT_ROOT / "web" / "static" / "favicon.svg"
    # tkinter can't use SVG directly, but we try .ico if present
    ico_path = PROJECT_ROOT / "web" / "static" / "favicon.ico"
    if ico_path.exists():
        try:
            root.iconbitmap(str(ico_path))
        except tk.TclError:
            pass

    app = SetupGUI(root)
    root.mainloop()


if __name__ == "__main__":
    main()
